<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
    <Using Include="Bank.Specs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bank.Api\Bank.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Samples.cs" Link="Samples.cs" />
  </ItemGroup>

</Project>
